[package]
name = "jdb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0"
nix = { version = "0.30", features = ["ptrace", "signal"] }
ratatui = "0.29"
tui-textarea = { version = "0.7", features = ["search"] }
